# Use the ubuntu:20.04
#From ubuntu:20.04
# Use the python 3.9
From python:3.9

#RUN apt install -y python3 python3-pip

COPY requirements.txt /
RUN pip install -r requirements.txt
#RUN pip3 install -r requirements.txt
